baseURL = "https://binariaos.com.py"
languageCode = "es-la"
title = "BinariaOS App || Desarrollo, Web, Diseño, Asucnión, Paraguay"
theme = "hugo-theme-shell"
# Note: This is for the meta description, which is different from the "description" displayed in the terminal.
description = "Welcome to BinariaOS || Desarrollo, Web, Diseño, Asucnión, Paraguay"

[Params]
  favicon ="favicon.ico"
  [Params.Terminal]
  # Note: color schema
  # Note: You can choose between
  # Note: ["monokai", "powershell", "gruvbox_light", "gruvbox_dark", "solarized_light", "solarized_dark", "ubuntu", "retro"]
  # Note: If you want to use the Goph theme, set it to "goph" (See README.md)
  schema = "monokai"

  # Note: in terminal
  # [userName]@[pcName]:~/$ cd [workDir]
  # [userName]@[pcName]:~/[workDir]$  cat [profile]
  #
  # [description]
  #
  # Note: if you set Params.Tree > use = true
  # [userName]@[pcName]:~/[workDir]$ tree ./[folderName]/
  # ./[folderName]/
  # ...
  # Note: result of the tree command
  userName = "Oski"
  pcName = "sistema01"

  # Note: speed at which text is displayed on the terminal
  # Note: if set to 0, typing animation will be disabled
  # Note:
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  ps1Delay = 5 # prompt speed : [userName]@[pcName]:~/$ , [userName]@[pcName]:~/[workDir]$
  stdoutDelay = 5 # stdout speed : [description] , files in Params.Tree
  commandDelay = 80 # command speed : cd [workDir] , cat [profile] , tree ./[folderName]/

  terminalDelay = 15 #: deprecated

  # Note: speed at which text is displayed on the activity pages
  # Note: if set to 0, typing animation will be disabled
  # Note: 
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  titleDelay = 5 # title speed : "title" in front matter
  contentDelay = 5 # content speed : content in .md file

  #activityDelay = 5 #: deprecated

  description = """
  Ready-
  Bienvenido a BinariaOS
  Diseño y desarrollo web
  Nuestro compromiso es crecer 
  con usted y su emprendimiento
  Adelantando el futuro...
  """

  # Note: If you want to use a Markdown file, you can use the following
  # description = "/description.md"
  # Note: and put the description.md in /content/description.md

  [Params.Tree]
  use = true
  folderName = "/main/activity"
  # Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
    files = [
        ["Main SIte", "https://go.binariaos.com.py"],
        ["e-Commerce", "https://shop.binariaos.com.py"],
        ["WordPress", "https://sites.binariaos.com.py"],
        ["MS-DOS", "https://msdos.binariaos.com.py"],
        ["Dev in Go", "/works/go.md"],
        ["Hugo Framework", "/works/hugo.md"],
        ["Contact!", "https://wa.me/595981480801"]
    ]
   
[module]
  [module.hugoVersion]
    extended = true
    min = "0.85.0"
